name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Generate private key and certificate
      run: |
        openssl req -newkey rsa:2048 -nodes -keyout private.key -x509 -days 365 -out code_signing.crt -subj "/C=US/ST=State/L=City/O=Organization/OU=Unit/CN=yourdomain.com"

    - name: Create PKCS#12 keystore
      run: openssl pkcs12 -export -in code_signing.crt -inkey private.key -out code_signing.p12 -name code_signing -passout pass:yourpassphrase

    - name: Import PKCS#12 into Java keystore
      run: |
        keytool -importkeystore -deststorepass yourpassphrase -destkeypass yourpassphrase -destkeystore code_signing.jks -srckeystore code_signing.p12 -srcstoretype PKCS12 -srcstorepass yourpassphrase -alias code_signing

    - name: Sign JAR file
      run: jarsigner -keystore code_signing.jks -storepass yourpassphrase -keypass yourpassphrase -signedjar target/SampleJavaApp-1.0-SNAPSHOT-signed.jar target/SampleJavaApp-1.0-SNAPSHOT.jar code_signing

    - name: Verify JAR file signature
      run: jarsigner -verify -verbose -certs target/SampleJavaApp-1.0-SNAPSHOT-signed.jar

    - name: Upload signed JAR file
      uses: actions/upload-artifact@v3
      with:
        name: SampleJavaApp-signed
        path: target/SampleJavaApp-1.0-SNAPSHOT-signed.jar
